<?php
/**
 * Created by PhpStorm.
 * User: Maksim Sergeevich (doctorpepper608@gmail.com)
 * Date: 20.01.2016
 * Time: 13:50
 */

namespace frontend\controllers;

use backend\modules\pages\models\Pages;
use backend\modules\seo\models\SEO;
use common\models\WbpActiveRecord;
use Yii;
use yii\web\Controller;
use frontend\models\RegisterForm;
use frontend\models\LoginForm;
use frontend\models\Callback;
use backend\modules\subscribe\models\Subscribe;

class BaseController extends Controller
{
    public $page;
    public $support;
    public $subMenu;
    public $breadcrumbs = [];
    public $registerForm;
    public $callback;
    public $modelSubscribe;
    public $loginFormModel;
    public $cartTotal;


    public function beforeAction($action)
    {
        $session = Yii::$app->session;
        if(!$session->isActive){$session->open();}
        $cart = $session->get('cart');
        $this->cartTotal = 0;
        if(is_array($cart)) {
            foreach ($cart as $key => $value) {
                $this->cartTotal += $value['price'] * $value['qty'];
            }
        }
        $this->modelSubscribe = new Subscribe();
        $this->modelSubscribe->return = $_SERVER['REQUEST_URI'];
        $this->registerForm = new RegisterForm();
        $this->callback = new Callback(['scenario' => Callback::FRONTEND_ADD_SCENARIO]);
        $this->loginFormModel = new LoginForm();
//        $this->modelSubscribe = new Subscribe(['scenario' => Subscribe::FRONTEND_SUBSCRIBE]);
//        $this->modelSubscribe->return = $_SERVER['REQUEST_URI'];

        $href = $action->id;

        if ($href == 'generic-page' && isset($_GET['href'])) $href = $_GET['href'];
        if (Yii::$app->controller->id != 'site') $href = Yii::$app->controller->id;

        $this->page = Pages::find()->where([
            'href' => $href,
            'status' => 1,
        ])->one();

        if (!$this->page)
            $this->page = new Pages();
        else {
            SEO::setByModel($this->page);
        }

        if ($this->page->parent_page > 0) {
            $this->parent_page = Pages::findOne(['id' => $this->page->parent_page, 'status' => WbpActiveRecord::STATUS_ACTIVE]);
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }



}