<?php

namespace frontend\models;

use yii\helpers\ArrayHelper;

class Callback extends \backend\modules\contacts\models\Contacts
{

    const FRONTEND_ADD_SCENARIO = 'frontend';

    public $return;

    public function init()
    {
        $this->return=$_SERVER['REQUEST_URI'];
        parent::init();
    }

    public function rules()
    {

        $rules = [
            //make request part
            [['fname', 'phone'], 'safe', 'on'=>Callback::FRONTEND_ADD_SCENARIO],
            [['fname', 'phone'], 'required', 'message' => 'Это обязательное поле', 'on'=>Callback::FRONTEND_ADD_SCENARIO],
            ['phone', 'match', 'pattern' => '/^((\+?38)(-?\d{3})-?)?(\d{3})(-?\d{4})$/', 'message' => \Yii::t("app", 'Некорректный телефон'), 'on'=>Callback::FRONTEND_ADD_SCENARIO],
//            [['phone'], 'udokmeci\yii2PhoneValidator\PhoneValidator','country'=>'UA', 'message' => 'неверный формат телефона', 'on'=>Callback::FRONTEND_ADD_SCENARIO],

        ];

        return $rules;
    }

//    public function attributeLabels()
//    {
//        return [
//            'fname' => 'Имя',
//            'message' => 'Комментарии или пожелания',
//            'phone' => 'Телефон',
//        ];
//    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
